
import { Inter } from 'next/font/google'
import './globals.css'
import { ClerkProvider } from '@clerk/nextjs'
import { dark } from '@clerk/themes'
import CurrentUser from '@/components/shared/CurrentUser'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang='en' suppressHydrationWarning>
      <ClerkProvider
        appearance={{
          baseTheme: dark,
        }}>
        <body className={`${inter.className} mx-auto min-h-screen max-w-[1920px]`} suppressHydrationWarning>
          <CurrentUser />
          {children}
        </body>
      </ClerkProvider>
    </html>
  )
}
